// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Iel1SUWhNX_YTNFY3i-gLOPdrRrlghs',
    appId: '1:968383903122:web:886c7efc4a68cd385fbd4b',
    messagingSenderId: '968383903122',
    projectId: 'codelab-e0441',
    authDomain: 'codelab-e0441.firebaseapp.com',
    storageBucket: 'codelab-e0441.appspot.com',
    measurementId: 'G-XV0628BLLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZQqmC-dP33tHVWlAowJ6TB7KJODxOznc',
    appId: '1:968383903122:android:1e6fb86a42f08f335fbd4b',
    messagingSenderId: '968383903122',
    projectId: 'codelab-e0441',
    storageBucket: 'codelab-e0441.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp7t7LQQYwppDZPUcZ8AyggDD14V_2dso',
    appId: '1:968383903122:ios:10388584613607075fbd4b',
    messagingSenderId: '968383903122',
    projectId: 'codelab-e0441',
    storageBucket: 'codelab-e0441.appspot.com',
    iosBundleId: 'com.example.codelab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp7t7LQQYwppDZPUcZ8AyggDD14V_2dso',
    appId: '1:968383903122:ios:10388584613607075fbd4b',
    messagingSenderId: '968383903122',
    projectId: 'codelab-e0441',
    storageBucket: 'codelab-e0441.appspot.com',
    iosBundleId: 'com.example.codelab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Iel1SUWhNX_YTNFY3i-gLOPdrRrlghs',
    appId: '1:968383903122:web:19b35d0fdc4992475fbd4b',
    messagingSenderId: '968383903122',
    projectId: 'codelab-e0441',
    authDomain: 'codelab-e0441.firebaseapp.com',
    storageBucket: 'codelab-e0441.appspot.com',
    measurementId: 'G-F5CQCDK3YF',
  );
}
