// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKptnFk88NekRh-llpdv-Ke8uKxR8Jcpc',
    appId: '1:913804585862:web:ea859cb77bfc74fb601a07',
    messagingSenderId: '913804585862',
    projectId: 'codelab4-e7e00',
    authDomain: 'codelab4-e7e00.firebaseapp.com',
    storageBucket: 'codelab4-e7e00.firebasestorage.app',
    measurementId: 'G-YJNKBV586F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ6RzANWqJ-M8BN9zRzGGhLrm4SBsg6Tk',
    appId: '1:913804585862:android:d9fc470714ed0df3601a07',
    messagingSenderId: '913804585862',
    projectId: 'codelab4-e7e00',
    storageBucket: 'codelab4-e7e00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk9i7nHYumffCI70smnP4OJnwBRN-RWjA',
    appId: '1:913804585862:ios:5a68cb13c1274aa7601a07',
    messagingSenderId: '913804585862',
    projectId: 'codelab4-e7e00',
    storageBucket: 'codelab4-e7e00.firebasestorage.app',
    iosBundleId: 'com.example.newCodelab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk9i7nHYumffCI70smnP4OJnwBRN-RWjA',
    appId: '1:913804585862:ios:5a68cb13c1274aa7601a07',
    messagingSenderId: '913804585862',
    projectId: 'codelab4-e7e00',
    storageBucket: 'codelab4-e7e00.firebasestorage.app',
    iosBundleId: 'com.example.newCodelab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKptnFk88NekRh-llpdv-Ke8uKxR8Jcpc',
    appId: '1:913804585862:web:a0e7590f8fb8ed04601a07',
    messagingSenderId: '913804585862',
    projectId: 'codelab4-e7e00',
    authDomain: 'codelab4-e7e00.firebaseapp.com',
    storageBucket: 'codelab4-e7e00.firebasestorage.app',
    measurementId: 'G-30F75S6C27',
  );
}
